"""Integration abstract base class."""

from __future__ import annotations

import abc
from dataclasses import replace
from typing import Any, Callable, Dict, List, Optional, Tuple, cast

from agentkit.runtime.tools.registry import (
    ToolHandler,
    ToolRegistry,
    ToolSpec,
    provider_safe_tool_name,
)


def tool(
    *,
    description: str,
    parameters: Dict[str, Any],
    risk: Optional[str] = None,
    tags: tuple[str, ...] = (),
    enabled: bool = True,
) -> Callable[[Any], Any]:
    """Decorator to declare a method as a tool on an Integration subclass."""

    def decorator(fn: Any) -> Any:
        fn.__tool_spec__ = dict(  # type: ignore[attr-defined]
            description=description,
            parameters=parameters,
            risk=risk,
            tags=tags,
            enabled=enabled,
        )
        return fn

    return decorator


Tool = tool


class Integration(abc.ABC):
    """Abstract base for a namespace-scoped collection of tools.

    Subclasses declare a `namespace` string and implement `tools()` returning
    a list of (ToolSpec, handler) pairs. The Integration prefixes each tool
    catalog name as `{namespace}.{tool_name}` when registering into a
    ToolRegistry. The provider-facing name is normalized to a provider-safe
    identifier.

    Alternatively, decorate handler methods with @tool and `tools()` will be
    auto-generated by scanning the instance for decorated methods.
    """

    @property
    @abc.abstractmethod
    def namespace(self) -> str:
        """The namespace prefix for all tools in this integration."""
        ...

    def tools(self) -> List[Tuple[ToolSpec, ToolHandler]]:
        """Collect @tool-decorated methods. Override to return tuples manually."""
        result: List[Tuple[ToolSpec, ToolHandler]] = []
        for attr_name in dir(self):
            if attr_name.startswith("_"):
                continue
            method = getattr(self, attr_name, None)
            spec_meta = getattr(method, "__tool_spec__", None)
            if spec_meta is None:
                # Check the underlying function for unbound descriptors
                raw = getattr(type(self), attr_name, None)
                spec_meta = getattr(raw, "__tool_spec__", None)
            if spec_meta is not None and callable(method):
                spec = ToolSpec(
                    name=attr_name,
                    description=spec_meta["description"],
                    parameters=spec_meta["parameters"],
                    risk=spec_meta["risk"],
                    tags=spec_meta["tags"],
                    enabled=spec_meta["enabled"],
                )
                result.append((spec, cast(ToolHandler, method)))
        return result

    def register(self, registry: ToolRegistry) -> None:
        """Register all tools into the given registry, namespace-prefixed."""
        for spec, handler in self.tools():
            catalog_name = f"{self.namespace}.{spec.name}"
            prefixed = replace(
                spec,
                name=provider_safe_tool_name(catalog_name),
                catalog_name=catalog_name,
            )
            registry.register(prefixed)(handler)
