import type { Provider } from "../providers.js";

export const PYTHON_SDK_RANGE = ">=0.2.0b1,<0.3";

export function pythonAgentTemplate(provider: Provider): string {
  return `"""Minimal kaji scaffold -- generated by \`kaji init\`."""

from __future__ import annotations

import asyncio
import kaji


async def main() -> None:
    runtime = (
        kaji.AgentBuilder()
        .provider(kaji.get_provider(${JSON.stringify(provider)}))
        .system_prompt("You are a helpful assistant.")
        .build()
    )
    result = await runtime.turn("Say hello.")
    final_sequence = max(event.sequence or 0 for event in result.events)
    print(f"text={result.text}")
    print(f"turn_id={result.turn_id}")
    print(f"final_sequence={final_sequence}")


if __name__ == "__main__":
    asyncio.run(main())
`;
}

const PYTHON_EXTRAS: Record<Provider, string> = {
  mock: "kaji",
  openai: "kaji[openai]",
  anthropic: "kaji[anthropic]",
};

function resolvePythonRequirement(provider: Provider): string {
  return PYTHON_EXTRAS[provider];
}

export function pythonRequirementsTemplate(provider: Provider): string {
  return `${resolvePythonRequirement(provider)}${PYTHON_SDK_RANGE}\n`;
}

export function pythonEnvTemplate(provider: Provider): string {
  const credentials: Record<Provider, string> = {
    mock: "# No provider credentials required.",
    openai: "OPENAI_API_KEY=",
    anthropic: "ANTHROPIC_API_KEY=",
  };
  const credential = credentials[provider];
  return `# kaji provider: ${provider}\nKAJI_MODEL_PROVIDER=${provider}\n${credential}\n`;
}
