"""Template strings for `kaji init`."""

from __future__ import annotations


def agent_template(provider: str) -> str:
    return f'''"""Minimal kaji scaffold -- generated by `kaji init`."""

from __future__ import annotations

import asyncio
import os

import kaji


async def main() -> None:
    provider_name = os.environ.get("KAJI_MODEL_PROVIDER", {provider!r})
    runtime = (
        kaji.AgentBuilder()
        .provider(kaji.get_provider(provider_name))
        .system_prompt("You are a helpful assistant.")
        .build()
    )
    result = await runtime.turn("Say hello.")
    print(result.text)


if __name__ == "__main__":
    asyncio.run(main())
'''


def env_template(provider: str) -> str:
    return f"""# kaji
KAJI_MODEL_PROVIDER={provider}

# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
# GEMINI_API_KEY=...
# KIMI_API_KEY=...
"""
