"""Stream consumer priority constants."""

from src.workers.helpers.redis_constants import (
    TOOL_RESULT_DLQ_DEAD_KEY,
    TOOL_RESULT_DLQ_KEY,
    TOOL_RESULT_DLQ_MAX_DRAIN,
    TOOL_RESULT_DLQ_MAX_RETRIES,
    VOICE_INPUT_DLQ_DEAD_KEY,
    VOICE_INPUT_DLQ_KEY,
    VOICE_INPUT_DLQ_MAX_DRAIN,
    VOICE_INPUT_DLQ_MAX_RETRIES,
)

__all__ = [
    "TOOL_RESULT_DLQ_DEAD_KEY",
    "TOOL_RESULT_DLQ_KEY",
    "TOOL_RESULT_DLQ_MAX_DRAIN",
    "TOOL_RESULT_DLQ_MAX_RETRIES",
    "VOICE_INPUT_DLQ_DEAD_KEY",
    "VOICE_INPUT_DLQ_KEY",
    "VOICE_INPUT_DLQ_MAX_DRAIN",
    "VOICE_INPUT_DLQ_MAX_RETRIES",
]
