"""AgentKit command line helpers."""

from __future__ import annotations

import argparse
from pathlib import Path


AGENT_TEMPLATE = '''"""Minimal AgentKit runtime scaffold — generated by `agentkit init`.

Set AGENTKIT_MODEL_PROVIDER (openai or anthropic) and the matching API key in
.env.example (copy it to .env), then run this file with `python agent.py`.
"""

from __future__ import annotations

import asyncio
import os

import agentkit


class ExampleIntegration:
    """Register your tools here. Replace this with your own integration."""

    def register(self, registry: agentkit.ToolRegistry) -> None:
        spec = agentkit.ToolSpec(
            name="get_time",
            description="Return the current server time as an epoch timestamp.",
            parameters={"type": "object", "properties": {}, "required": []},
        )

        @registry.register(spec)
        async def _get_time(ctx: agentkit.ToolContext, args: dict) -> dict:
            import time
            return {"epoch": time.time()}


async def main() -> None:
    bus = agentkit.InMemoryEventBus()
    store = agentkit.InMemoryEventStore()

    provider_name = os.environ.get("AGENTKIT_MODEL_PROVIDER", "openai")
    provider = agentkit.GetProvider(provider_name)

    runtime = (
        agentkit.AgentBuilder()
        .provider(provider)
        .integration(ExampleIntegration())
        .system_prompt("You are a helpful assistant.")
        .build(bus=bus, store=store)
    )

    await store.append(agentkit.UserMessage(session_id="s1", content="What time is it?"))
    await runtime.run_turn("s1")

    events = await store.get_events("s1")
    for e in events:
        print(e.type, getattr(e, "content", getattr(e, "delta", "")))


if __name__ == "__main__":
    asyncio.run(main())
'''


ENV_TEMPLATE = """# Provider selection — set one of these and the matching API key.
AGENTKIT_MODEL_PROVIDER=openai
# AGENTKIT_MODEL_PROVIDER=anthropic

# API keys — uncomment and fill in the one you use.
# OPENAI_API_KEY=sk-...
# OPENAI_MODEL=gpt-4o

# ANTHROPIC_API_KEY=sk-ant-...
"""


def _write(path: Path, content: str, *, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.write_text(content)
    return True


def init_project(target: Path, *, force: bool = False) -> list[Path]:
    """Create a minimal local AgentKit scaffold."""
    target.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for filename, content in {
        "agent.py": AGENT_TEMPLATE,
        ".env.example": ENV_TEMPLATE,
    }.items():
        path = target / filename
        if _write(path, content, force=force):
            written.append(path)
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="agentkit")
    subcommands = parser.add_subparsers(dest="command", required=True)

    init_parser = subcommands.add_parser("init", help="Create a minimal scaffold")
    init_parser.add_argument("path", nargs="?", default=".")
    init_parser.add_argument("--force", action="store_true", help="Overwrite files")

    args = parser.parse_args(argv)
    if args.command == "init":
        written = init_project(Path(args.path), force=args.force)
        for path in written:
            print(path)
        return 0
    return 1


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
