"""Integration abstract base class."""

from __future__ import annotations

import abc
import logging
from dataclasses import replace
from typing import Any, Callable, Dict, List, Optional, Tuple, Type, Union, cast

from pydantic import BaseModel

from kaji.runtime.tools.registry import (
    ToolHandler,
    ToolRegistry,
    ToolRisk,
    ToolSpec,
    provider_safe_tool_name,
)

logger = logging.getLogger(__name__)


def _warn_on_sanitize(original: str, sanitized: str) -> None:
    logger.warning(
        "tool name %r sanitized to %r for provider compatibility",
        original,
        sanitized,
    )


def tool(
    *,
    description: str,
    parameters: Union[Dict[str, Any], Type[BaseModel]],
    risk: Optional[ToolRisk] = None,
    tags: tuple[str, ...] = (),
    enabled: bool = True,
    parallel_safe: bool = False,
    timeout_ms: int | None = None,
) -> Callable[[Any], Any]:
    """Decorator to declare a method as a tool on an Integration subclass.

    ``parameters`` accepts either a JSON Schema dict or a Pydantic ``BaseModel``
    subclass; the model is converted to JSON Schema at registration time.
    """
    if isinstance(parameters, type) and issubclass(parameters, BaseModel):
        parameters_schema = parameters.model_json_schema(mode="validation")
    else:
        parameters_schema = parameters

    def decorator(fn: Any) -> Any:
        fn.__tool_spec__ = dict(  # type: ignore[attr-defined]
            description=description,
            parameters=parameters_schema,
            risk=risk,
            tags=tags,
            enabled=enabled,
            parallel_safe=parallel_safe,
            timeout_ms=timeout_ms,
        )
        return fn

    return decorator


class Integration(abc.ABC):
    """Abstract base for a namespace-scoped collection of tools.

    Subclasses declare a `namespace` string and implement `tools()` returning
    a list of (ToolSpec, handler) pairs. The Integration prefixes each tool
    catalog name as `{namespace}.{tool_name}` when registering into a
    ToolRegistry. The provider-facing name is normalized to a provider-safe
    identifier.

    Alternatively, decorate handler methods with @tool and `tools()` will be
    auto-generated by scanning the instance for decorated methods.
    """

    @property
    @abc.abstractmethod
    def namespace(self) -> str:
        """The namespace prefix for all tools in this integration."""
        ...

    def tools(self) -> List[Tuple[ToolSpec, ToolHandler]]:
        """Collect @tool-decorated methods. Override to return tuples manually."""
        result: List[Tuple[ToolSpec, ToolHandler]] = []
        for attr_name in dir(self):
            if attr_name.startswith("_"):
                continue
            method = getattr(self, attr_name, None)
            spec_meta = getattr(method, "__tool_spec__", None)
            if spec_meta is None:
                # Check the underlying function for unbound descriptors
                raw = getattr(type(self), attr_name, None)
                spec_meta = getattr(raw, "__tool_spec__", None)
            if spec_meta is not None and callable(method):
                spec = ToolSpec(
                    name=attr_name,
                    description=spec_meta["description"],
                    parameters=spec_meta["parameters"],
                    risk=spec_meta["risk"],
                    tags=spec_meta["tags"],
                    enabled=spec_meta["enabled"],
                    parallel_safe=spec_meta["parallel_safe"],
                    timeout_ms=spec_meta["timeout_ms"],
                )
                result.append((spec, cast(ToolHandler, method)))
        return result

    def register(self, registry: ToolRegistry) -> None:
        """Register all tools into the given registry, namespace-prefixed."""
        for spec, handler in self.tools():
            catalog_name = f"{self.namespace}.{spec.name}"
            prefixed = replace(
                spec,
                name=provider_safe_tool_name(catalog_name, on_mutate=_warn_on_sanitize),
                catalog_name=catalog_name,
            )
            registry.register(prefixed)(handler)
