"""Template strings for `kaji init`."""

from __future__ import annotations


def agent_template(provider: str) -> str:
    return f'''"""Minimal kaji scaffold -- generated by `kaji init`."""

from __future__ import annotations

import asyncio

import kaji


async def main() -> None:
    runtime = (
        kaji.AgentBuilder()
        .provider(kaji.get_provider("{provider}"))
        .system_prompt("You are a helpful assistant.")
        .build()
    )
    result = await runtime.turn("Say hello.")
    final_sequence = max(event.sequence or 0 for event in result.events)
    print(f"text={{result.text}}")
    print(f"turn_id={{result.turn_id}}")
    print(f"final_sequence={{final_sequence}}")


if __name__ == "__main__":
    asyncio.run(main())
'''


def env_template(provider: str) -> str:
    credentials = {
        "mock": "# No provider credentials required.",
        "openai": "OPENAI_API_KEY=",
        "anthropic": "ANTHROPIC_API_KEY=",
    }
    return f"""# kaji provider: {provider}
KAJI_MODEL_PROVIDER={provider}
{credentials[provider]}
"""
