"""Typed event definitions for the agent bus system."""

from app.core.event_envelope import (
    EVENT_SCHEMA_VERSION,
    EventEnvelope,
    build_event_envelope,
    is_supported_event_version,
    parse_event_envelope,
    to_redis_stream_fields,
)
from app.core.event_models import (
    AgentError,
    AgentGenerationComplete,
    AgentHandoff,
    AgentResponse,
    AgentSpeechSent,
    AgentStartedSpeaking,
    AgentStoppedSpeaking,
    Authorize,
    CustomReceived,
    DTMFInputEvent,
    DTMFOutputEvent,
    DTMFStoppedEvent,
    EndCall,
    LogMetric,
    ToolCall,
    ToolResult,
    TransferCall,
    UserStartedSpeaking,
    UserStoppedSpeaking,
    UserTranscriptionReceived,
    UserUnknownInputReceived,
)
from app.core.event_registry import (
    EventInstance,
    EventsRegistry,
    EventType,
    EventTypeOrAlias,
)

__all__ = [
    "EVENT_SCHEMA_VERSION",
    "AgentError",
    "AgentGenerationComplete",
    "AgentHandoff",
    "AgentResponse",
    "AgentSpeechSent",
    "AgentStartedSpeaking",
    "AgentStoppedSpeaking",
    "Authorize",
    "CustomReceived",
    "DTMFInputEvent",
    "DTMFOutputEvent",
    "DTMFStoppedEvent",
    "EndCall",
    "EventEnvelope",
    "EventInstance",
    "EventsRegistry",
    "EventType",
    "EventTypeOrAlias",
    "LogMetric",
    "ToolCall",
    "ToolResult",
    "TransferCall",
    "UserStartedSpeaking",
    "UserStoppedSpeaking",
    "UserTranscriptionReceived",
    "UserUnknownInputReceived",
    "build_event_envelope",
    "is_supported_event_version",
    "parse_event_envelope",
    "to_redis_stream_fields",
]
