"""
Constants for Redis keys, DLQs, TTLs, and configuration across agent/worker logic.
"""

TOOL_RESULT_PUBLISH_MAX_ATTEMPTS = 3
TOOL_RESULT_PUBLISH_BASE_RETRY_DELAY_SECONDS = 0.25
TOOL_RESULT_STREAM_MAXLEN = 10_000

# Outbox config
USER_UPDATE_OUTBOX_KEY = "outbox:user_updates:v1"
USER_UPDATE_OUTBOX_MAXLEN = 2_000
USER_UPDATE_OUTBOX_MAX_DRAIN = 100
USER_UPDATE_OUTBOX_TTL_SECONDS = 24 * 60 * 60
USER_UPDATE_OUTBOX_DLQ_KEY = "dlq:user_updates:v1"
USER_UPDATE_OUTBOX_DLQ_MAXLEN = 2_000
USER_UPDATE_OUTBOX_DLQ_TTL_SECONDS = 7 * 24 * 60 * 60

# Tool Result DLQ Config
TOOL_RESULT_DLQ_KEY = "dlq:tool_results:v1"
TOOL_RESULT_DLQ_DEAD_KEY = "dlq:tool_results:dead:v1"
TOOL_RESULT_DLQ_MAXLEN = 2_000
TOOL_RESULT_DLQ_MAX_DRAIN = 25
TOOL_RESULT_DLQ_MAX_RETRIES = 3
TOOL_RESULT_DLQ_TTL_SECONDS = 24 * 60 * 60
TOOL_RESULT_DLQ_DEAD_TTL_SECONDS = 7 * 24 * 60 * 60

# Voice Input DLQ Config
VOICE_INPUT_DLQ_KEY = "dlq:voice_input:v1"
VOICE_INPUT_DLQ_DEAD_KEY = "dlq:voice_input:dead:v1"
VOICE_INPUT_DLQ_MAXLEN = 2_000
VOICE_INPUT_DLQ_MAX_DRAIN = 25
VOICE_INPUT_DLQ_MAX_RETRIES = 3
VOICE_INPUT_DLQ_TTL_SECONDS = 24 * 60 * 60
VOICE_INPUT_DLQ_DEAD_TTL_SECONDS = 7 * 24 * 60 * 60

# Dedupe Config
TOOL_RESULT_SEEN_KEY_PREFIX = "tool_result:seen:v1:"
TOOL_RESULT_SEEN_TTL_SECONDS = 24 * 60 * 60

# Tool Exec Config
TOOL_CALL_RETRYABLE_TOOL_NAMES: frozenset[str] = frozenset()
TOOL_CALL_DEDUP_IN_PROGRESS_PREFIX = "tool_call:inflight:v1:"
TOOL_CALL_DEDUP_DONE_PREFIX = "tool_call:done:v1:"
TOOL_CALL_DEDUP_TTL_SECONDS = 24 * 60 * 60
TOOL_CALL_DEDUP_IN_PROGRESS_TTL_SECONDS = 5 * 60
