"""Update integrations table schema

Revision ID: 825310236a51
Revises: 9273bcb2cf30
Create Date: 2025-10-12 18:12:19.980487

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "825310236a51"
down_revision: Union[str, None] = "9273bcb2cf30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
