"""`agentkit gen` — generate tool stubs from an OpenAPI spec."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path

HTTP_METHODS = ("get", "post", "put", "patch", "delete", "head", "options", "trace")


def to_snake_case(s: str) -> str:
    s = re.sub(r"([A-Z])", r"_\1", s)
    s = re.sub(r"[-\s]+", "_", s)
    s = re.sub(r"[^a-zA-Z0-9_]", "", s)
    s = re.sub(r"_+", "_", s)
    return s.strip("_").lower()


def extract_path_params(path: str) -> list[str]:
    return re.findall(r"\{([^}]+)\}", path)


@dataclass
class ParsedOperation:
    operation_id: str
    fn_name: str
    method: str
    path: str
    summary: str
    tag: str | None
    path_params: list[str]
    risk: str


def parse_spec(spec: dict) -> list[ParsedOperation]:
    ops: list[ParsedOperation] = []
    for path, methods in (spec.get("paths") or {}).items():
        if not isinstance(methods, dict):
            continue
        for method in HTTP_METHODS:
            op = methods.get(method)
            if not op or not op.get("operationId"):
                continue
            ops.append(ParsedOperation(
                operation_id=op["operationId"],
                fn_name=to_snake_case(op["operationId"]),
                method=method.upper(),
                path=path,
                summary=op.get("summary") or op.get("description") or op["operationId"],
                tag=(op.get("tags") or [None])[0],
                path_params=extract_path_params(path),
                risk="read" if method == "get" else "write",
            ))
    return ops


def _infer_base_url(spec: dict) -> str:
    servers = spec.get("servers") or [{}]
    return servers[0].get("url") or "https://api.example.com"


def _infer_env_var(spec: dict) -> str:
    title = (spec.get("info") or {}).get("title") or "API"
    return to_snake_case(title).upper() + "_API_KEY"


def generate_python_file(spec: dict, ops: list[ParsedOperation], prefix: str) -> str:
    base = _infer_base_url(spec)
    env = _infer_env_var(spec)
    lines = [
        "# Auto-generated by agentkit gen. Do not edit.",
        "import os",
        "import httpx",
        "",
        f'BASE_URL = "{base}"',
        f'API_KEY = os.environ.get("{env}", "")',
        "",
        "TOOLS = [",
    ]
    for op in ops:
        name = f"{prefix}_{op.fn_name}" if prefix else op.fn_name
        props = ",\n            ".join(
            f'"{p}": {{"type": "string", "description": "{p} path param"}}' for p in op.path_params
        ) or "# no path params"
        required = (
            f', "required": [{", ".join(f"\"{p}\"" for p in op.path_params)}]'
            if op.path_params else ""
        )
        lines.append(
            f"    {{\n"
            f'        "name": "{name}",\n'
            f'        "description": {json.dumps(op.summary)},\n'
            f'        "parameters": {{\n'
            f'            "type": "object",\n'
            f'            "properties": {{{props}}}{required}\n'
            f'        }},\n'
            f'        "risk": "{op.risk}",\n'
            f"    }},"
        )
    lines.append("]")
    lines.append("")
    for op in ops:
        name = f"{prefix}_{op.fn_name}" if prefix else op.fn_name
        # path with {x} -> {args["x"]} style for str.format-like substitution
        url_path = re.sub(r"\{([^}]+)\}", r'{args["\1"]}', op.path)
        has_body = op.method not in ("GET", "HEAD", "OPTIONS")
        body_kwarg = ", json=args" if has_body else ""
        lines.append(
            f"async def {name}(args: dict) -> dict:\n"
            f'    url = f"{{BASE_URL}}{url_path}"\n'
            f"    async with httpx.AsyncClient() as c:\n"
            f'        r = await c.request("{op.method}", url, headers={{"Authorization": f"Bearer {{API_KEY}}"}}{body_kwarg})\n'
            f"        return r.json()\n"
        )
    return "\n".join(lines)


def generate_ts_file(spec: dict, ops: list[ParsedOperation], prefix: str) -> str:
    """Identical output to apps/cli generateTsFile. Duplicated to keep Python CLI standalone."""
    base = _infer_base_url(spec)
    env = _infer_env_var(spec)
    tools_entries = []
    for op in ops:
        name = f"{prefix}_{op.fn_name}" if prefix else op.fn_name
        props = ",\n".join(
            f'        {p}: {{ type: "string", description: "{p} path param" }}'
            for p in op.path_params
        ) or "        // no path params"
        required = (
            f"\n      required: [{', '.join(f'\"{p}\"' for p in op.path_params)}],"
            if op.path_params else ""
        )
        tag = f'\n    tags: ["{op.tag}"],' if op.tag else ""
        tools_entries.append(
            f"  {{\n"
            f'    name: "{name}",\n'
            f'    description: {json.dumps(op.summary)},\n'
            f"    parameters: {{\n"
            f'      type: "object",\n'
            f"      properties: {{\n{props}\n      }},{required}\n"
            f"    }},\n"
            f'    risk: "{op.risk}",{tag}\n'
            f"  }}"
        )
    handlers = []
    for op in ops:
        name = f"{prefix}_{op.fn_name}" if prefix else op.fn_name
        url_path = re.sub(r"\{([^}]+)\}", r"${args.\1}", op.path)
        has_body = op.method not in ("GET", "HEAD", "OPTIONS")
        body = "\n    body: JSON.stringify(args)," if has_body else ""
        ct = ', "Content-Type": "application/json"' if has_body else ""
        handlers.append(
            f"export async function {name}(args: Record<string, unknown>): Promise<unknown> {{\n"
            f"  const url = new URL(`${{BASE_URL}}{url_path}`);\n"
            f"  const r = await fetch(url.toString(), {{\n"
            f'    method: "{op.method}",\n'
            f'    headers: {{ Authorization: `Bearer ${{API_KEY}}`{ct} }},{body}\n'
            f"  }});\n"
            f"  return r.json();\n"
            f"}}"
        )
    return (
        "// Auto-generated by agentkit gen. Do not edit.\n"
        'import type { ToolSpec } from "@agentkit/sdk";\n\n'
        f'// Auth: set {env} in your environment\n'
        f'const BASE_URL = "{base}";\n'
        f'const API_KEY = process.env.{env} ?? "";\n\n'
        f"export const tools: ToolSpec[] = [\n{',\n'.join(tools_entries)},\n];\n\n"
        + "\n\n".join(handlers)
        + "\n"
    )


def add_parser(sub: argparse._SubParsersAction) -> None:
    p = sub.add_parser("gen", help="generate tool stubs from an OpenAPI spec")
    p.add_argument("--spec", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--prefix", default="")
    p.add_argument("--lang", choices=("ts", "python"), default="python")
    p.set_defaults(func=run)


def _load_spec(path: Path) -> dict:
    raw = path.read_text()
    if path.suffix.lower() == ".json":
        return json.loads(raw)
    if path.suffix.lower() in (".yaml", ".yml"):
        try:
            import yaml  # type: ignore
        except ImportError as e:
            raise SystemExit("YAML specs require PyYAML — pip install pyyaml or convert to JSON.") from e
        return yaml.safe_load(raw)
    try:
        return json.loads(raw)
    except json.JSONDecodeError as e:
        raise SystemExit(f"Failed to parse spec: {e}") from e


def run(args: argparse.Namespace) -> int:
    spec_path = Path(args.spec).resolve()
    out_dir = Path(args.out).resolve()
    if not spec_path.exists():
        print(f"Spec file not found: {spec_path}")
        return 1
    spec = _load_spec(spec_path)
    ops = parse_spec(spec)
    if not ops:
        print("No operations with operationId found in spec.")
        return 1
    out_dir.mkdir(parents=True, exist_ok=True)
    if args.lang == "python":
        out_file = out_dir / "tools.py"
        out_file.write_text(generate_python_file(spec, ops, args.prefix))
    else:
        out_file = out_dir / "index.ts"
        out_file.write_text(generate_ts_file(spec, ops, args.prefix))
    print(f"Wrote {out_file} ({len(ops)} tools)")
    return 0
