"""Template strings for `agentkit init`."""

from __future__ import annotations


def agent_template(provider: str) -> str:
    return f'''"""Minimal agentkit scaffold -- generated by `agentkit init`."""

from __future__ import annotations

import asyncio
import os

import agentkit


async def main() -> None:
    bus = agentkit.InMemoryEventBus()
    store = agentkit.InMemoryEventStore()
    provider_name = os.environ.get("AGENTKIT_MODEL_PROVIDER", {provider!r})
    runtime = (
        agentkit.AgentBuilder()
        .provider(agentkit.get_provider(provider_name))
        .system_prompt("You are a helpful assistant.")
        .build(bus=bus, store=store)
    )
    await store.append(agentkit.UserMessage(session_id="s1", content="Hello!"))
    await runtime.run_turn("s1")
    for e in await store.get_events("s1"):
        print(e.type, getattr(e, "content", getattr(e, "delta", "")))


if __name__ == "__main__":
    asyncio.run(main())
'''


def env_template(provider: str) -> str:
    return f"""# agentkit
AGENTKIT_MODEL_PROVIDER={provider}

# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
# GEMINI_API_KEY=...
# KIMI_API_KEY=...
"""
