name: lint / go

on:
  push:
    branches: [main]
    paths:
      - "ryo/api/**"
      - "ryo/consumer/**"
      - ".github/actions/setup-go-cache/**"
      - ".github/workflows/go.lint.yml"
  pull_request:
    paths:
      - "ryo/api/**"
      - "ryo/consumer/**"
      - ".github/actions/setup-go-cache/**"
      - ".github/workflows/go.lint.yml"

jobs:
  api:
    name: ryo/api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ryo/api
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go-cache
        with:
          working-directory: ryo/api

      - name: Vet
        run: go vet ./...

  consumer:
    name: ryo/consumer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ryo/consumer
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-go-cache
        with:
          working-directory: ryo/consumer

      - name: Vet
        run: go vet ./...
