name: format / python

on:
  push:
    branches: [main]
    paths:
      - "kaji/sdk/**"
      - "kaji/serve/**"
      - ".github/actions/setup-python-uv/**"
      - ".github/workflows/python.format.yml"
  pull_request:
    paths:
      - "kaji/sdk/**"
      - "kaji/serve/**"
      - ".github/actions/setup-python-uv/**"
      - ".github/workflows/python.format.yml"

permissions:
  contents: read

jobs:
  sdk:
    name: kaji/sdk
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: kaji/sdk
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ./.github/actions/setup-python-uv
        with:
          working-directory: kaji/sdk

      - name: Check formatting
        run: uv run ruff format --check .

  serve:
    name: kaji/serve
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: kaji/serve
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ./.github/actions/setup-python-uv
        with:
          working-directory: kaji/serve

      - name: Check formatting
        run: uv run ruff format --check .
